//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DBContentElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBContentElement() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.DBContentElement", typeof(DBContentElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 免费电子游戏 的本地化字符串。
        /// </summary>
        public static string AgBetMemo_Game {
            get {
                return ResourceManager.GetString("AgBetMemo_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 局号：{0} 的本地化字符串。
        /// </summary>
        public static string AgBetMemo_GameCode {
            get {
                return ResourceManager.GetString("AgBetMemo_GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string AgBetMemo_GameTypeName {
            get {
                return ResourceManager.GetString("AgBetMemo_GameTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string AgBetMemo_PlatformTypeName {
            get {
                return ResourceManager.GetString("AgBetMemo_PlatformTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string AgBetMemo_PlayTypeName {
            get {
                return ResourceManager.GetString("AgBetMemo_PlayTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string AgBetMemo_RoundName {
            get {
                return ResourceManager.GetString("AgBetMemo_RoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌号：{0} 的本地化字符串。
        /// </summary>
        public static string AgBetMemo_TableCode {
            get {
                return ResourceManager.GetString("AgBetMemo_TableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，亏赢：{1}，场景编号：{2}，开始时间：{3}，结束时间：{4}，房间号：{5}，倍数：{6}，发射的子弹价值：{7}，打到的鱼价值：{8} 的本地化字符串。
        /// </summary>
        public static string AgFishBetMemo1 {
            get {
                return ResourceManager.GetString("AgFishBetMemo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，捕鱼场景 {1} 参与抽奖，中奖金额：{2} 的本地化字符串。
        /// </summary>
        public static string AgFishBetMemo2 {
            get {
                return ResourceManager.GetString("AgFishBetMemo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕鱼王转账 的本地化字符串。
        /// </summary>
        public static string AgFishBetMemo3 {
            get {
                return ResourceManager.GetString("AgFishBetMemo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，获取本场捕鱼王，奖励：{1}，场景编号：{2}，开始时间：{3}，结束时间：{4}，房间号：{5}，倍数：{6} 的本地化字符串。
        /// </summary>
        public static string AgFishBetMemo7 {
            get {
                return ResourceManager.GetString("AgFishBetMemo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, 游戏平台名称：{1}, 游戏名称：{2}, 注单号：{3}, 游戏平台的下注项目：{4}, 下注金额：{5}, 收到下注的时间戳：{6}, 结算时间：{7} 的本地化字符串。
        /// </summary>
        public static string AWCSPMemo {
            get {
                return ResourceManager.GetString("AWCSPMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充提红利金，获得 红包{0}元 的本地化字符串。
        /// </summary>
        public static string BonusFlowMemo {
            get {
                return ResourceManager.GetString("BonusFlowMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整流水, 原流水:{0},新流水:{1}, 备注:{2} 的本地化字符串。
        /// </summary>
        public static string ChangeAccumulateFlowAmount {
            get {
                return ResourceManager.GetString("ChangeAccumulateFlowAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户余额总和低于{0}元超过{1}天，清0流水 的本地化字符串。
        /// </summary>
        public static string ClearAccumulateFlowAmount {
            get {
                return ResourceManager.GetString("ClearAccumulateFlowAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}佣金 的本地化字符串。
        /// </summary>
        public static string CommissionByDate {
            get {
                return ResourceManager.GetString("CommissionByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理代存转入,{0} 的本地化字符串。
        /// </summary>
        public static string DepositFromVIPAgentParent {
            get {
                return ResourceManager.GetString("DepositFromVIPAgentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string Flexible {
            get {
                return ResourceManager.GetString("Flexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流水:{0}倍 的本地化字符串。
        /// </summary>
        public static string FlowMultiple {
            get {
                return ResourceManager.GetString("FlowMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏名称：{0} 的本地化字符串。
        /// </summary>
        public static string FYESCategory {
            get {
                return ResourceManager.GetString("FYESCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏代码：{0} 的本地化字符串。
        /// </summary>
        public static string FYESCode {
            get {
                return ResourceManager.GetString("FYESCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子订单ID：{0}，游戏名称：{1}，盘口类型：{2}@赔率：{3}，子订单状态：{4}，下单时间：{5}，派奖时间：{6} 的本地化字符串。
        /// </summary>
        public static string FYESComboDetail {
            get {
                return ResourceManager.GetString("FYESComboDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘口类型：{0}@赔率：{1}，投注金额：{2}，订单状态：{3}，下单时间：{4}，派奖时间：{5} 的本地化字符串。
        /// </summary>
        public static string FYESComboInfo {
            get {
                return ResourceManager.GetString("FYESComboInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘口类型：{0}@赔率：{1}，投注金额：{2}，下单时间：{3}，派奖时间：{4} 的本地化字符串。
        /// </summary>
        public static string FYESGameInfo {
            get {
                return ResourceManager.GetString("FYESGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单类型：{0}，订单号：{1} 的本地化字符串。
        /// </summary>
        public static string FYESOrderInfo {
            get {
                return ResourceManager.GetString("FYESOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统赠送彩金, {0}, {1} 的本地化字符串。
        /// </summary>
        public static string GivePrizeMemo {
            get {
                return ResourceManager.GetString("GivePrizeMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统补发奖金, {0} 的本地化字符串。
        /// </summary>
        public static string GivePrizeMemoByPrize {
            get {
                return ResourceManager.GetString("GivePrizeMemoByPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台返水主帐户 的本地化字符串。
        /// </summary>
        public static string MainAccountRebate {
            get {
                return ResourceManager.GetString("MainAccountRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}手动领取返水 的本地化字符串。
        /// </summary>
        public static string ManualReceiveRebateMoney {
            get {
                return ResourceManager.GetString("ManualReceiveRebateMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注: {0} 的本地化字符串。
        /// </summary>
        public static string MemoMessage {
            get {
                return ResourceManager.GetString("MemoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 返水 的本地化字符串。
        /// </summary>
        public static string ReceiveRebateMoneyByDate {
            get {
                return ResourceManager.GetString("ReceiveRebateMoneyByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扣减余额, {0} 的本地化字符串。
        /// </summary>
        public static string ReduceAvailableScoreMemo {
            get {
                return ResourceManager.GetString("ReduceAvailableScoreMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子商户提款 的本地化字符串。
        /// </summary>
        public static string SubMerchantTransferIn {
            get {
                return ResourceManager.GetString("SubMerchantTransferIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统赠送彩金 的本地化字符串。
        /// </summary>
        public static string SystemGivePrize {
            get {
                return ResourceManager.GetString("SystemGivePrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统补发奖金 的本地化字符串。
        /// </summary>
        public static string SystemReissuePrize {
            get {
                return ResourceManager.GetString("SystemReissuePrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值 的本地化字符串。
        /// </summary>
        public static string VIAdminMoneyInfo {
            get {
                return ResourceManager.GetString("VIAdminMoneyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首存豪礼 畅领5888,首存金额：{0}元,累計有效投注：{1},获得礼金：{2} 的本地化字符串。
        /// </summary>
        public static string VIP5888BonusActivityMemo {
            get {
                return ResourceManager.GetString("VIP5888BonusActivityMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 為下級{0}代理,流水倍數{1}倍,{2} 的本地化字符串。
        /// </summary>
        public static string VIPAgentDepositForChild {
            get {
                return ResourceManager.GetString("VIPAgentDepositForChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理钱包转入 的本地化字符串。
        /// </summary>
        public static string VIPAgentTransferToCenter {
            get {
                return ResourceManager.GetString("VIPAgentTransferToCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值 的本地化字符串。
        /// </summary>
        public static string VIPCardMoneyInfo {
            get {
                return ResourceManager.GetString("VIPCardMoneyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参与活动金额{0}元，充值订单号：{1} 的本地化字符串。
        /// </summary>
        public static string VIPDepositActivityMemo {
            get {
                return ResourceManager.GetString("VIPDepositActivityMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP等级变更, {0} 变更为 {1} 的本地化字符串。
        /// </summary>
        public static string VIPLevelDownLogMemo {
            get {
                return ResourceManager.GetString("VIPLevelDownLogMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP晋级礼金,晋升{0} 的本地化字符串。
        /// </summary>
        public static string VIPLevelUpMoneyPrizeMemo {
            get {
                return ResourceManager.GetString("VIPLevelUpMoneyPrizeMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运大转盘, 获得活动礼金{0}元 的本地化字符串。
        /// </summary>
        public static string VIPLuckyWheelActivityBonusMemo {
            get {
                return ResourceManager.GetString("VIPLuckyWheelActivityBonusMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运大转盘, 获得VIP积分{0} 的本地化字符串。
        /// </summary>
        public static string VIPLuckyWheelActivityPointsMemo {
            get {
                return ResourceManager.GetString("VIPLuckyWheelActivityPointsMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP月存款福利,参与活动金额{0}元，充值订单号：{1} 的本地化字符串。
        /// </summary>
        public static string VIPMonthlyDepositActivityMemo {
            get {
                return ResourceManager.GetString("VIPMonthlyDepositActivityMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值 的本地化字符串。
        /// </summary>
        public static string VIPOnlineManualMoneyInfo {
            get {
                return ResourceManager.GetString("VIPOnlineManualMoneyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值 的本地化字符串。
        /// </summary>
        public static string VIPOnlineMoneyInfo {
            get {
                return ResourceManager.GetString("VIPOnlineMoneyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 积分规则调整 的本地化字符串。
        /// </summary>
        public static string VIPPointRuleAdjust {
            get {
                return ResourceManager.GetString("VIPPointRuleAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}生日礼金 的本地化字符串。
        /// </summary>
        public static string VIPReceivedBirthdayGiftMoney {
            get {
                return ResourceManager.GetString("VIPReceivedBirthdayGiftMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}月红包 的本地化字符串。
        /// </summary>
        public static string VIPReceivedMonthlyRedEnvelopeMoney {
            get {
                return ResourceManager.GetString("VIPReceivedMonthlyRedEnvelopeMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}周红包 的本地化字符串。
        /// </summary>
        public static string VIPReceivedWeeklyRedEnvelopeMoney {
            get {
                return ResourceManager.GetString("VIPReceivedWeeklyRedEnvelopeMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现申请 的本地化字符串。
        /// </summary>
        public static string VIPWithdrawApply {
            get {
                return ResourceManager.GetString("VIPWithdrawApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现确认 的本地化字符串。
        /// </summary>
        public static string VIPWithdrawConfirm {
            get {
                return ResourceManager.GetString("VIPWithdrawConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USDT提款,提取RMB:{0},匯率:1:{1}(USDT:RMB),折算USDT:{2} 的本地化字符串。
        /// </summary>
        public static string VIPWithdrawUsdtMemo {
            get {
                return ResourceManager.GetString("VIPWithdrawUsdtMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串关投注 的本地化字符串。
        /// </summary>
        public static string WagerCombo {
            get {
                return ResourceManager.GetString("WagerCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单一投注 的本地化字符串。
        /// </summary>
        public static string WagerSingle {
            get {
                return ResourceManager.GetString("WagerSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提款至中心钱包 的本地化字符串。
        /// </summary>
        public static string WithdrawFromVIPAgent {
            get {
                return ResourceManager.GetString("WithdrawFromVIPAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现退款 的本地化字符串。
        /// </summary>
        public static string WithdrawRefund {
            get {
                return ResourceManager.GetString("WithdrawRefund", resourceCulture);
            }
        }
    }
}
