//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ThirdPartyApiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseReturnModel", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.ReturnModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.ThirdPartyApiService.BaseReturnDataModelOfTPGameOpenParamZWylxVPn))]
    public partial class BaseReturnModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseReturnDataModelOfTPGameOpenParamZWylxVPn", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.ReturnModel")]
    [System.SerializableAttribute()]
    public partial class BaseReturnDataModelOfTPGameOpenParamZWylxVPn : Web.ThirdPartyApiService.BaseReturnModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.ThirdPartyApiService.TPGameOpenParam DataModelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.ThirdPartyApiService.TPGameOpenParam DataModel {
            get {
                return this.DataModelField;
            }
            set {
                if ((object.ReferenceEquals(this.DataModelField, value) != true)) {
                    this.DataModelField = value;
                    this.RaisePropertyChanged("DataModel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TPGameOpenParam", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.Param.ThirdParty")]
    [System.SerializableAttribute()]
    public partial class TPGameOpenParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenGameModeValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpenGameModeValue {
            get {
                return this.OpenGameModeValueField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenGameModeValueField, value) != true)) {
                    this.OpenGameModeValueField = value;
                    this.RaisePropertyChanged("OpenGameModeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityModel", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.Entity.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.ThirdPartyApiService.FrontsideMenu))]
    public partial class BaseEntityModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateDateTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDateText {
            get {
                return this.CreateDateTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateTextField, value) != true)) {
                    this.CreateDateTextField = value;
                    this.RaisePropertyChanged("CreateDateText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUser {
            get {
                return this.CreateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserField, value) != true)) {
                    this.CreateUserField = value;
                    this.RaisePropertyChanged("CreateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateDateText {
            get {
                return this.UpdateDateTextField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateDateTextField, value) != true)) {
                    this.UpdateDateTextField = value;
                    this.RaisePropertyChanged("UpdateDateText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateUser {
            get {
                return this.UpdateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateUserField, value) != true)) {
                    this.UpdateUserField = value;
                    this.RaisePropertyChanged("UpdateUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FrontsideMenu", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.Entity")]
    [System.SerializableAttribute()]
    public partial class FrontsideMenu : Web.ThirdPartyApiService.BaseEntityModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppSortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemoteCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppSort {
            get {
                return this.AppSortField;
            }
            set {
                if ((this.AppSortField.Equals(value) != true)) {
                    this.AppSortField = value;
                    this.RaisePropertyChanged("AppSort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngName {
            get {
                return this.EngNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EngNameField, value) != true)) {
                    this.EngNameField = value;
                    this.RaisePropertyChanged("EngName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameCode {
            get {
                return this.GameCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameCodeField, value) != true)) {
                    this.GameCodeField = value;
                    this.RaisePropertyChanged("GameCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuName {
            get {
                return this.MenuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuNameField, value) != true)) {
                    this.MenuNameField = value;
                    this.RaisePropertyChanged("MenuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PicName {
            get {
                return this.PicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PicNameField, value) != true)) {
                    this.PicNameField = value;
                    this.RaisePropertyChanged("PicName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteCode {
            get {
                return this.RemoteCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteCodeField, value) != true)) {
                    this.RemoteCodeField = value;
                    this.RaisePropertyChanged("RemoteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sort {
            get {
                return this.SortField;
            }
            set {
                if ((this.SortField.Equals(value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThirdPartyApiService.IThirdPartyApiWCFService")]
    public interface IThirdPartyApiWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThirdPartyApiWCFService/GetForwardGameUrl", ReplyAction="http://tempuri.org/IThirdPartyApiWCFService/GetForwardGameUrlResponse")]
        Web.ThirdPartyApiService.BaseReturnDataModelOfTPGameOpenParamZWylxVPn GetForwardGameUrl(string productCode, string loginInfoJson, bool isMobile, string correlationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThirdPartyApiWCFService/GetForwardGameUrl", ReplyAction="http://tempuri.org/IThirdPartyApiWCFService/GetForwardGameUrlResponse")]
        System.Threading.Tasks.Task<Web.ThirdPartyApiService.BaseReturnDataModelOfTPGameOpenParamZWylxVPn> GetForwardGameUrlAsync(string productCode, string loginInfoJson, bool isMobile, string correlationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThirdPartyApiWCFService/GetActiveFrontsideMenu", ReplyAction="http://tempuri.org/IThirdPartyApiWCFService/GetActiveFrontsideMenuResponse")]
        Web.ThirdPartyApiService.FrontsideMenu GetActiveFrontsideMenu(string productCode, string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThirdPartyApiWCFService/GetActiveFrontsideMenu", ReplyAction="http://tempuri.org/IThirdPartyApiWCFService/GetActiveFrontsideMenuResponse")]
        System.Threading.Tasks.Task<Web.ThirdPartyApiService.FrontsideMenu> GetActiveFrontsideMenuAsync(string productCode, string gameCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IThirdPartyApiWCFServiceChannel : Web.ThirdPartyApiService.IThirdPartyApiWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThirdPartyApiWCFServiceClient : System.ServiceModel.ClientBase<Web.ThirdPartyApiService.IThirdPartyApiWCFService>, Web.ThirdPartyApiService.IThirdPartyApiWCFService {
        
        public ThirdPartyApiWCFServiceClient() {
        }
        
        public ThirdPartyApiWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThirdPartyApiWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThirdPartyApiWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThirdPartyApiWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web.ThirdPartyApiService.BaseReturnDataModelOfTPGameOpenParamZWylxVPn GetForwardGameUrl(string productCode, string loginInfoJson, bool isMobile, string correlationId) {
            return base.Channel.GetForwardGameUrl(productCode, loginInfoJson, isMobile, correlationId);
        }
        
        public System.Threading.Tasks.Task<Web.ThirdPartyApiService.BaseReturnDataModelOfTPGameOpenParamZWylxVPn> GetForwardGameUrlAsync(string productCode, string loginInfoJson, bool isMobile, string correlationId) {
            return base.Channel.GetForwardGameUrlAsync(productCode, loginInfoJson, isMobile, correlationId);
        }
        
        public Web.ThirdPartyApiService.FrontsideMenu GetActiveFrontsideMenu(string productCode, string gameCode) {
            return base.Channel.GetActiveFrontsideMenu(productCode, gameCode);
        }
        
        public System.Threading.Tasks.Task<Web.ThirdPartyApiService.FrontsideMenu> GetActiveFrontsideMenuAsync(string productCode, string gameCode) {
            return base.Channel.GetActiveFrontsideMenuAsync(productCode, gameCode);
        }
    }
}
