import {
  DeviceType,
  IntroductionType,
  MyPostType,
  PostType,
  ReviewStatusType,
  MyMessageViewType,
  MyBossShopType,
  MyBossAppointmentType,
  MyBossPostStatus,
  MyCollectViewType,
  MyBookingStatusType,
} from "@/enums";
import {
  BannerModel,
  ChinaCityInfo,
  MediaModel,
  OptionItemModel,
  CenterModel,
  ProductDetailModel,
  ZeroOneSettingModel,
  PageParamModel,
  LabelFilterModel,
  ScrollStatusModel,
  CertificationModel,
  PostFilterOptionsModel,
  OfficialDetailModel,
  OfficialShopDetailModel,
  HomeStatusInfoModel,
  ImageItemModel,
  WaterfallModel,
} from "@/models";
import { defaultCityArea } from "@/defaultConfig";

export const state = {
  isLoading: false,
  showAnnouncement: true,
  announcementContent: "",
  noReminderPreventFraud: true,
  reminderUnixTime: 0,
  currentPage: 1,
  city: defaultCityArea[0] as ChinaCityInfo | undefined,
  selectedValue: [] as string[],
  homeBannerList: [] as BannerModel[],
  bannerList: [] as BannerModel[],
  mediaSelectList: [] as MediaModel[],
  messageType: {} as OptionItemModel,
  messageTypeList: [] as OptionItemModel[],
  sortType: {} as OptionItemModel,
  postType: PostType.None as PostType,
  centerInfo: {} as CenterModel,
  logonMode: 0 as number,
  zeroOneSetting: {} as ZeroOneSettingModel,
  productDetail: {} as ProductDetailModel,
  officialDetail: {} as OfficialDetailModel,
  officialShopDetail: {} as OfficialShopDetailModel,
  myBossShopDetail: {} as OfficialShopDetailModel,
  privateMessageAvatar: "",
  privateMessageShopName: "",
  searchStatus: false,
  adminContact: "",
  deviceType: DeviceType.PC as DeviceType,
  scrollStatus: {} as ScrollStatusModel,
  pageInfo: {
    pageNo: 0,
    pageSize: 30,
    ts: "",
  } as PageParamModel,
  filter: {} as LabelFilterModel,
  publishName: IntroductionType.Square,
  myPostViewName: MyPostType.MyOverview,
  isImageZoomMode: false,
  certificationStatus: {} as CertificationModel,
  postFilterInfo: {} as PostFilterOptionsModel,
  imageCache: new Map<string, Map<string, string>>(),
  unlockViewStatus: PostType.Square,
  postManageStatus: ReviewStatusType.None,
  homeStatusInfo: {} as HomeStatusInfoModel,
  selectPostDataWherePostType: PostType.Square,
  messageViewStatus: MyMessageViewType.ComplaintPost,
  myBossShop: MyBossShopType.Appointment,
  myCollectViewTypeStatus: MyCollectViewType.Official,
  myBossShopAppointmentOrderStatus: MyBossAppointmentType.TakeOrders,
  myBossShopPostStatus: MyBossPostStatus.RemovedFromShelves,
  isShowImage: true,
  myOrderSelectPageType: MyBookingStatusType.InService,
  isBossShopEdit: false,
  favoritePosts: [] as string[],
  imageShowItem: {} as ImageItemModel,
  waterfallStatus: {} as WaterfallModel,
  waterfallTop: 0,
};

export type State = typeof state;
