//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinanceElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinanceElement() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.FinanceElement", typeof(FinanceElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 账户姓名 的當地語系化字串。
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 账户 的當地語系化字串。
        /// </summary>
        public static string AccountWallet {
            get {
                return ResourceManager.GetString("AccountWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支付宝定额快充 的當地語系化字串。
        /// </summary>
        public static string AlipayPdd {
            get {
                return ResourceManager.GetString("AlipayPdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 充值金额 的當地語系化字串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申请金额 的當地語系化字串。
        /// </summary>
        public static string ApplicationAmount {
            get {
                return ResourceManager.GetString("ApplicationAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申请时间 的當地語系化字串。
        /// </summary>
        public static string ApplicationDate {
            get {
                return ResourceManager.GetString("ApplicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申请当下折算币别金额 的當地語系化字串。
        /// </summary>
        public static string ApplyAmount {
            get {
                return ResourceManager.GetString("ApplyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申请当下汇率 的當地語系化字串。
        /// </summary>
        public static string ApplyRate {
            get {
                return ResourceManager.GetString("ApplyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申请RMB金额 的當地語系化字串。
        /// </summary>
        public static string ApplyScores {
            get {
                return ResourceManager.GetString("ApplyScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行卡号 的當地語系化字串。
        /// </summary>
        public static string BankCardNo {
            get {
                return ResourceManager.GetString("BankCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行类型 的當地語系化字串。
        /// </summary>
        public static string BankType {
            get {
                return ResourceManager.GetString("BankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行类型 的當地語系化字串。
        /// </summary>
        public static string BankTypeName {
            get {
                return ResourceManager.GetString("BankTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 红利金 的當地語系化字串。
        /// </summary>
        public static string BonusAmount {
            get {
                return ResourceManager.GetString("BonusAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 钱包类型 的當地語系化字串。
        /// </summary>
        public static string CoinWalletType {
            get {
                return ResourceManager.GetString("CoinWalletType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 实际换汇后币别金额 的當地語系化字串。
        /// </summary>
        public static string DealAmount {
            get {
                return ResourceManager.GetString("DealAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apollo处理時实际汇率 的當地語系化字串。
        /// </summary>
        public static string DealRate {
            get {
                return ResourceManager.GetString("DealRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 描述 的當地語系化字串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上分时间 的當地語系化字串。
        /// </summary>
        public static string EditDate {
            get {
                return ResourceManager.GetString("EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提现备注 的當地語系化字串。
        /// </summary>
        public static string HandleMemo {
            get {
                return ResourceManager.GetString("HandleMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建单时间 的當地語系化字串。
        /// </summary>
        public static string InDate {
            get {
                return ResourceManager.GetString("InDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 充值备注 的當地語系化字串。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 充值类型 的當地語系化字串。
        /// </summary>
        public static string MoneyInType {
            get {
                return ResourceManager.GetString("MoneyInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未到账 的當地語系化字串。
        /// </summary>
        public static string MoneyOutstanding {
            get {
                return ResourceManager.GetString("MoneyOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已到账 的當地語系化字串。
        /// </summary>
        public static string MoneyReceived {
            get {
                return ResourceManager.GetString("MoneyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 汇款时间 的當地語系化字串。
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 充值单号 的當地語系化字串。
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已处理 的當地語系化字串。
        /// </summary>
        public static string OrderStatusDone {
            get {
                return ResourceManager.GetString("OrderStatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正在处理 的當地語系化字串。
        /// </summary>
        public static string OrderStatusProcessing {
            get {
                return ResourceManager.GetString("OrderStatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已退款 的當地語系化字串。
        /// </summary>
        public static string OrderStatusRefunded {
            get {
                return ResourceManager.GetString("OrderStatusRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待确认 的當地語系化字串。
        /// </summary>
        public static string OrderStatusWaitingForConfirm {
            get {
                return ResourceManager.GetString("OrderStatusWaitingForConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申请时间 的當地語系化字串。
        /// </summary>
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 处理时间 的當地語系化字串。
        /// </summary>
        public static string ProcessTime {
            get {
                return ResourceManager.GetString("ProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 状态 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系统银行开户人 的當地語系化字串。
        /// </summary>
        public static string SysBankUser {
            get {
                return ResourceManager.GetString("SysBankUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用户账号 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 钱包 的當地語系化字串。
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收款地址 的當地語系化字串。
        /// </summary>
        public static string WalletAddr {
            get {
                return ResourceManager.GetString("WalletAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 保证金 的當地語系化字串。
        /// </summary>
        public static string WarrantAmount {
            get {
                return ResourceManager.GetString("WarrantAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提现单号 的當地語系化字串。
        /// </summary>
        public static string WithdrawOrderID {
            get {
                return ResourceManager.GetString("WithdrawOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提现类型 的當地語系化字串。
        /// </summary>
        public static string WithdrawType {
            get {
                return ResourceManager.GetString("WithdrawType", resourceCulture);
            }
        }
    }
}
