//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GivePrizesElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GivePrizesElement() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.GivePrizesElement", typeof(GivePrizesElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 活动 的當地語系化字串。
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 调帐 的當地語系化字串。
        /// </summary>
        public static string Adjustments {
            get {
                return ResourceManager.GetString("Adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行类型 的當地語系化字串。
        /// </summary>
        public static string BankType {
            get {
                return ResourceManager.GetString("BankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 佣金 的當地語系化字串。
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 充值 的當地語系化字串。
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流水倍数 的當地語系化字串。
        /// </summary>
        public static string FlowMultiple {
            get {
                return ResourceManager.GetString("FlowMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 格式错误！ 的當地語系化字串。
        /// </summary>
        public static string FormatIncorrect {
            get {
                return ResourceManager.GetString("FormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金额 的當地語系化字串。
        /// </summary>
        public static string MoneyAmount {
            get {
                return ResourceManager.GetString("MoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必须大于0 的當地語系化字串。
        /// </summary>
        public static string MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必须大于等于0 的當地語系化字串。
        /// </summary>
        public static string MustBePositive {
            get {
                return ResourceManager.GetString("MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不是一个有效的 的當地語系化字串。
        /// </summary>
        public static string NotAnValidData {
            get {
                return ResourceManager.GetString("NotAnValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请选择 的當地語系化字串。
        /// </summary>
        public static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派奖 的當地語系化字串。
        /// </summary>
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 彩金类型 的當地語系化字串。
        /// </summary>
        public static string PrizesType {
            get {
                return ResourceManager.GetString("PrizesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紅包 的當地語系化字串。
        /// </summary>
        public static string RedPacket {
            get {
                return ResourceManager.GetString("RedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只允许有{0}位小数 的當地語系化字串。
        /// </summary>
        public static string TooManyDecimal {
            get {
                return ResourceManager.GetString("TooManyDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 钱包类型 的當地語系化字串。
        /// </summary>
        public static string WalletType {
            get {
                return ResourceManager.GetString("WalletType", resourceCulture);
            }
        }
    }
}
