//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageElement() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.MessageElement", typeof(MessageElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 确认要删除吗？ 的當地語系化字串。
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 比例至少一条规则 的當地語系化字串。
        /// </summary>
        public static string AtLeastOneRule {
            get {
                return ResourceManager.GetString("AtLeastOneRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 审核列表已存在相同用户的待审核资料，请再确认 的當地語系化字串。
        /// </summary>
        public static string AuditDataByUserIsExists {
            get {
                return ResourceManager.GetString("AuditDataByUserIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 审核列表已存在相同的新{0}待审核，请再确认 的當地語系化字串。
        /// </summary>
        public static string AuditErrorMessage {
            get {
                return ResourceManager.GetString("AuditErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}, {1}, 备注:{2} 的當地語系化字串。
        /// </summary>
        public static string AuditOperationContent {
            get {
                return ResourceManager.GetString("AuditOperationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行卡帐号不正确 的當地語系化字串。
        /// </summary>
        public static string BandCardNoIsWrong {
            get {
                return ResourceManager.GetString("BandCardNoIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行卡姓名不正确 的當地語系化字串。
        /// </summary>
        public static string BandCardUserIsWrong {
            get {
                return ResourceManager.GetString("BandCardUserIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行卡已被绑定 的當地語系化字串。
        /// </summary>
        public static string BankCardAlreadyBind {
            get {
                return ResourceManager.GetString("BankCardAlreadyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 绑定失败，暂不支持绑定此类银行卡 的當地語系化字串。
        /// </summary>
        public static string BankCardBindFailed {
            get {
                return ResourceManager.GetString("BankCardBindFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 银行卡卡号不正确 的當地語系化字串。
        /// </summary>
        public static string BankCardInValid {
            get {
                return ResourceManager.GetString("BankCardInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请至个人中心&gt;银行卡管理&gt;绑定银行卡 的當地語系化字串。
        /// </summary>
        public static string BindBankCard {
            get {
                return ResourceManager.GetString("BindBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 设定档错误 的當地語系化字串。
        /// </summary>
        public static string ConfigInvalid {
            get {
                return ResourceManager.GetString("ConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 确认要重置用户{0}{1}吗？若是，请填写原因 的當地語系化字串。
        /// </summary>
        public static string ConfirmResetPasswordWithReason {
            get {
                return ResourceManager.GetString("ConfirmResetPasswordWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 天 的當地語系化字串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 6-16位字符，可输入英文、数字与符号 的當地語系化字串。
        /// </summary>
        public static string dynamicPasswordFormatFail {
            get {
                return ResourceManager.GetString("dynamicPasswordFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 邮箱格式错误 的當地語系化字串。
        /// </summary>
        public static string EmailRuleFail {
            get {
                return ResourceManager.GetString("EmailRuleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 不可为空值 的當地語系化字串。
        /// </summary>
        public static string FieldIsNotAllowEmpty {
            get {
                return ResourceManager.GetString("FieldIsNotAllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 格式错误 的當地語系化字串。
        /// </summary>
        public static string FormatFail {
            get {
                return ResourceManager.GetString("FormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 资料从FTP Server远端下载异常 的當地語系化字串。
        /// </summary>
        public static string FtpDownloadFileNotSuccessfully {
            get {
                return ResourceManager.GetString("FtpDownloadFileNotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 谷歌身份验证是一全新帐户安全工具，2步骤轻松绑定身份，确保您的帐户更有保障 的當地語系化字串。
        /// </summary>
        public static string GoogleAuthenticatorDescription {
            get {
                return ResourceManager.GetString("GoogleAuthenticatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Google身分验证即将到期 的當地語系化字串。
        /// </summary>
        public static string GoogleAuthenticatorExpiredWarning {
            get {
                return ResourceManager.GetString("GoogleAuthenticatorExpiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小时 的當地語系化字串。
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您已成功通过身分验证，请按确定，进入银行卡信息管理页 的當地語系化字串。
        /// </summary>
        public static string IdentityIsPassAndGotoUpdateBankCardPage {
            get {
                return ResourceManager.GetString("IdentityIsPassAndGotoUpdateBankCardPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 输入资料有误，无法进行验证 的當地語系化字串。
        /// </summary>
        public static string InputInformationWrong {
            get {
                return ResourceManager.GetString("InputInformationWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登录IP地址不合法 的當地語系化字串。
        /// </summary>
        public static string InvalidIpAddress {
            get {
                return ResourceManager.GetString("InvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IP {0} 不允许后台登录 的當地語系化字串。
        /// </summary>
        public static string IpAddressNotAllow {
            get {
                return ResourceManager.GetString("IpAddressNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 确认要退款吗？退款后积分将退还到用户帐号 的當地語系化字串。
        /// </summary>
        public static string IsConfirmRefund {
            get {
                return ResourceManager.GetString("IsConfirmRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可为负值 的當地語系化字串。
        /// </summary>
        public static string IsNotAllowNegative {
            get {
                return ResourceManager.GetString("IsNotAllowNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只能设定万位整数 的當地語系化字串。
        /// </summary>
        public static string IsNotTenThousandFormat {
            get {
                return ResourceManager.GetString("IsNotTenThousandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登录已过期！ 的當地語系化字串。
        /// </summary>
        public static string LoginIsExpired {
            get {
                return ResourceManager.GetString("LoginIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登录已过期，请重新登录 的當地語系化字串。
        /// </summary>
        public static string LoginIsExpiredPleaseloginAgain {
            get {
                return ResourceManager.GetString("LoginIsExpiredPleaseloginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 6-16位字符, 需包含英文和数字 的當地語系化字串。
        /// </summary>
        public static string LoginPasswordFormatFail {
            get {
                return ResourceManager.GetString("LoginPasswordFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最大搜寻天数为{0}天 的當地語系化字串。
        /// </summary>
        public static string MaxSearchDaysIsArg {
            get {
                return ResourceManager.GetString("MaxSearchDaysIsArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 方法名称 的當地語系化字串。
        /// </summary>
        public static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分 的當地語系化字串。
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手机号码格式错误 的當地語系化字串。
        /// </summary>
        public static string MobileFormatFail {
            get {
                return ResourceManager.GetString("MobileFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份验证通过，请输入用户{0}新的邮箱并填写备注 的當地語系化字串。
        /// </summary>
        public static string ModEmailUserDataMsg {
            get {
                return ResourceManager.GetString("ModEmailUserDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}：{1} -&gt; {2} 的當地語系化字串。
        /// </summary>
        public static string ModifyData {
            get {
                return ResourceManager.GetString("ModifyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份验证通过，请输入用户{0}新的手机号码并填写备注 的當地語系化字串。
        /// </summary>
        public static string ModMobileUserDataMsg {
            get {
                return ResourceManager.GetString("ModMobileUserDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 10-16位字符，需包含大小写英文和数字 的當地語系化字串。
        /// </summary>
        public static string MoneyPasswordFormatFail {
            get {
                return ResourceManager.GetString("MoneyPasswordFormatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 资金密码错误 的當地語系化字串。
        /// </summary>
        public static string MoneyPasswordIsNotValid {
            get {
                return ResourceManager.GetString("MoneyPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密码不可与近{0}天内设置的密码相同 的當地語系化字串。
        /// </summary>
        public static string NewPasswordSameWithOldInNDays {
            get {
                return ResourceManager.GetString("NewPasswordSameWithOldInNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 没有数据需要导出！ 的當地語系化字串。
        /// </summary>
        public static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 无编辑权限 的當地語系化字串。
        /// </summary>
        public static string NoEditPermission {
            get {
                return ResourceManager.GetString("NoEditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 无权限 的當地語系化字串。
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前没有渠道支援, 请选择其它充值方式 的當地語系化字串。
        /// </summary>
        public static string NoRechargeChannel {
            get {
                return ResourceManager.GetString("NoRechargeChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 暂不支持{0}充值 的當地語系化字串。
        /// </summary>
        public static string NoSupportSomeKindServiceType {
            get {
                return ResourceManager.GetString("NoSupportSomeKindServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 旧密码错误 的當地語系化字串。
        /// </summary>
        public static string OldPasswordIsNotValid {
            get {
                return ResourceManager.GetString("OldPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密码不能和旧密码相同 的當地語系化字串。
        /// </summary>
        public static string OldPasswordSameAsNewPassword {
            get {
                return ResourceManager.GetString("OldPasswordSameAsNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【查询】与【旧版查询】差别仅在于程式查询的方式与速度不同，
        ///查询结果应该要是一样的，若有不同请协助回报开发
        ///试运行确认无误后会将旧版查询移除 的當地語系化字串。
        /// </summary>
        public static string OldVersionSearchMemo {
            get {
                return ResourceManager.GetString("OldVersionSearchMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查询的时间区间限制为{0}天內！ 的當地語系化字串。
        /// </summary>
        public static string OnlyBetweenNDays {
            get {
                return ResourceManager.GetString("OnlyBetweenNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 仅可查询今日起近{0}天內资料！ 的當地語系化字串。
        /// </summary>
        public static string OnlyWithinNDays {
            get {
                return ResourceManager.GetString("OnlyWithinNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0},修改{1}, 原{2}：{3}, 新{4}：{5}, 备注：{6} 的當地語系化字串。
        /// </summary>
        public static string OperationContent {
            get {
                return ResourceManager.GetString("OperationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作失败 的當地語系化字串。
        /// </summary>
        public static string OperationFail {
            get {
                return ResourceManager.GetString("OperationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作成功 的當地語系化字串。
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可输入超过 {0} 个文字 的當地語系化字串。
        /// </summary>
        public static string OverInputLength {
            get {
                return ResourceManager.GetString("OverInputLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请填写备注信息 的當地語系化字串。
        /// </summary>
        public static string PlsFillMemo {
            get {
                return ResourceManager.GetString("PlsFillMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请选择开户银行 的當地語系化字串。
        /// </summary>
        public static string PlsSelectBankCardType {
            get {
                return ResourceManager.GetString("PlsSelectBankCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请先綁定銀行卡，方可提现 的當地語系化字串。
        /// </summary>
        public static string PlzBindBankCard {
            get {
                return ResourceManager.GetString("PlzBindBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请先绑定银行卡 的當地語系化字串。
        /// </summary>
        public static string PlzBindBankCardFirst {
            get {
                return ResourceManager.GetString("PlzBindBankCardFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请输入分红比例 的當地語系化字串。
        /// </summary>
        public static string PlzInputCommissionPercent {
            get {
                return ResourceManager.GetString("PlzInputCommissionPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请输入输赢上限 的當地語系化字串。
        /// </summary>
        public static string PlzInputMaxProfitLossRange {
            get {
                return ResourceManager.GetString("PlzInputMaxProfitLossRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请输入输赢下限 的當地語系化字串。
        /// </summary>
        public static string PlzInputMinProfitLossRange {
            get {
                return ResourceManager.GetString("PlzInputMinProfitLossRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请输入资金密码 的當地語系化字串。
        /// </summary>
        public static string PlzInputMoneyPassword {
            get {
                return ResourceManager.GetString("PlzInputMoneyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请输入{0}动态密码 的當地語系化字串。
        /// </summary>
        public static string PlzInputSomeKindPin {
            get {
                return ResourceManager.GetString("PlzInputSomeKindPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请填写有效的英文跟数字组合 的當地語系化字串。
        /// </summary>
        public static string PlzLetterAndNumber {
            get {
                return ResourceManager.GetString("PlzLetterAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请先绑定谷歌身份验证 的當地語系化字串。
        /// </summary>
        public static string PlzVerifyGoogleAuthenticator {
            get {
                return ResourceManager.GetString("PlzVerifyGoogleAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 为提升您的帐户安全性，请重设您的资金密码加强密码长度与复杂度 的當地語系化字串。
        /// </summary>
        public static string ResetMoneyPasswordDescription {
            get {
                return ResourceManager.GetString("ResetMoneyPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 保存成功 的當地語系化字串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每月4号前要查询上月整月分红盈亏，
        ///可勾选【仅查询上月分红结算的盈亏】
        ///过滤上个月分红结算后第三方回传的盈亏
        ///(每月4号后此功能无作用)
        ///勾选后请使用【查询】【查询全线】；
        ///【旧版查询】与【旧版查询全线】不支援此功能 的當地語系化字串。
        /// </summary>
        public static string SearchLastMonthBonusMemo {
            get {
                return ResourceManager.GetString("SearchLastMonthBonusMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 秒 的當地語系化字串。
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}身份验证绑定已过期，详情请联系客服 的當地語系化字串。
        /// </summary>
        public static string SomeKindAuthenticatorExpired {
            get {
                return ResourceManager.GetString("SomeKindAuthenticatorExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}身份{1}完成 的當地語系化字串。
        /// </summary>
        public static string SomeKindAuthenticatorVerifyCompleted {
            get {
                return ResourceManager.GetString("SomeKindAuthenticatorVerifyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}动态密码不能为空 的當地語系化字串。
        /// </summary>
        public static string SomeKindPinIsEmpty {
            get {
                return ResourceManager.GetString("SomeKindPinIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}动态密码错误 的當地語系化字串。
        /// </summary>
        public static string SomeKindPinIsNotValid {
            get {
                return ResourceManager.GetString("SomeKindPinIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同步Bak失敗 的當地語系化字串。
        /// </summary>
        public static string SyncBakFail {
            get {
                return ResourceManager.GetString("SyncBakFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 转账功能已被关闭，请联系客服 的當地語系化字串。
        /// </summary>
        public static string TransferToChildIsDisabled {
            get {
                return ResourceManager.GetString("TransferToChildIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除绑定身分验证完成 的當地語系化字串。
        /// </summary>
        public static string UnverifiedAuthenticatorByBackSideWebSuccessfully {
            get {
                return ResourceManager.GetString("UnverifiedAuthenticatorByBackSideWebSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 资金密码更新失败 的當地語系化字串。
        /// </summary>
        public static string UpdateMoneyPwdFail {
            get {
                return ResourceManager.GetString("UpdateMoneyPwdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新的资金密码已传送至 {0} 的當地語系化字串。
        /// </summary>
        public static string UpdateMoneyPwdSuccess {
            get {
                return ResourceManager.GetString("UpdateMoneyPwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新成功，请重新查询！ 的當地語系化字串。
        /// </summary>
        public static string UpdateSuccessAndRefresh {
            get {
                return ResourceManager.GetString("UpdateSuccessAndRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登录密码更新失败 的當地語系化字串。
        /// </summary>
        public static string UpdateUserPwdFail {
            get {
                return ResourceManager.GetString("UpdateUserPwdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登录密码更新成功，新密码为 {0} 的當地語系化字串。
        /// </summary>
        public static string UpdateUserPwdSuccess {
            get {
                return ResourceManager.GetString("UpdateUserPwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您绑定的USDT收款地址错误, 请重新确认 的當地語系化字串。
        /// </summary>
        public static string UsdtAddressWrong {
            get {
                return ResourceManager.GetString("UsdtAddressWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该用户未曾绑定 的當地語系化字串。
        /// </summary>
        public static string UserHasNotSetAuthenticator {
            get {
                return ResourceManager.GetString("UserHasNotSetAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该用户未曾设置资金密码，请该用户先进行初始化资料设置 的當地語系化字串。
        /// </summary>
        public static string UserHasNotSetMoneyPwd {
            get {
                return ResourceManager.GetString("UserHasNotSetMoneyPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用户资料已经变更，请重新登录 的當地語系化字串。
        /// </summary>
        public static string UserInfoChangedPleaseloginAgain {
            get {
                return ResourceManager.GetString("UserInfoChangedPleaseloginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该用户尚未进行初始化，请用户于前台初始化设定设置邮箱 的當地語系化字串。
        /// </summary>
        public static string UserInitializeIncomplete {
            get {
                return ResourceManager.GetString("UserInitializeIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用户名格式错误 的當地語系化字串。
        /// </summary>
        public static string UserNameFormatIsNotValid {
            get {
                return ResourceManager.GetString("UserNameFormatIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该用户未绑定银行卡无法进行身份验证 的當地語系化字串。
        /// </summary>
        public static string UserUnboundBankCard {
            get {
                return ResourceManager.GetString("UserUnboundBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份验证失败 的當地語系化字串。
        /// </summary>
        public static string UserVaildFailed {
            get {
                return ResourceManager.GetString("UserVaildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您已成功通过资料验证 的當地語系化字串。
        /// </summary>
        public static string YouPassedDataVerification {
            get {
                return ResourceManager.GetString("YouPassedDataVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您的上级为你转账 {0} 元，请注意查收 的當地語系化字串。
        /// </summary>
        public static string YourParentTransferMoneyToYou {
            get {
                return ResourceManager.GetString("YourParentTransferMoneyToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 转账¥{0}到{1}账户失败，请联系客服 的當地語系化字串。
        /// </summary>
        public static string YouTransferInFailly {
            get {
                return ResourceManager.GetString("YouTransferInFailly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您成功转账 ¥{0}到{1}账户 的當地語系化字串。
        /// </summary>
        public static string YouTransferInSuccessfully {
            get {
                return ResourceManager.GetString("YouTransferInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 从{0}账户提款¥{1}失败，请重试 的當地語系化字串。
        /// </summary>
        public static string YouTransferOutFailly {
            get {
                return ResourceManager.GetString("YouTransferOutFailly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您成功从{0}账户提款 ¥{1} 的當地語系化字串。
        /// </summary>
        public static string YouTransferOutSuccessfully {
            get {
                return ResourceManager.GetString("YouTransferOutSuccessfully", resourceCulture);
            }
        }
    }
}
