//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserRelatedElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRelatedElement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.UserRelatedElement", typeof(UserRelatedElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主账户余额.
        /// </summary>
        public static string AvailableScoresNameByTypeAgent {
            get {
                return ResourceManager.GetString("AvailableScoresNameByTypeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主账户余额(中心).
        /// </summary>
        public static string AvailableScoresNameByTypeDirect {
            get {
                return ResourceManager.GetString("AvailableScoresNameByTypeDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 余额.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行卡号.
        /// </summary>
        public static string BankCard {
            get {
                return ResourceManager.GetString("BankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行类型.
        /// </summary>
        public static string BankType {
            get {
                return ResourceManager.GetString("BankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行户名.
        /// </summary>
        public static string CardUser {
            get {
                return ResourceManager.GetString("CardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下级转账开关.
        /// </summary>
        public static string ChildTransferSwitch {
            get {
                return ResourceManager.GetString("ChildTransferSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (清空).
        /// </summary>
        public static string ClearContent {
            get {
                return ResourceManager.GetString("ClearContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该{0}已被绑定，请重新输入.
        /// </summary>
        public static string DuplicateContent {
            get {
                return ResourceManager.GetString("DuplicateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记?.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冻结.
        /// </summary>
        public static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冻结余额.
        /// </summary>
        public static string FreezeScoresNameByTypeAgent {
            get {
                return ResourceManager.GetString("FreezeScoresNameByTypeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冻结余额(中心).
        /// </summary>
        public static string FreezeScoresNameByTypeDirect {
            get {
                return ResourceManager.GetString("FreezeScoresNameByTypeDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主账户.
        /// </summary>
        public static string MainAccount {
            get {
                return ResourceManager.GetString("MainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ****.
        /// </summary>
        public static string MaskContent {
            get {
                return ResourceManager.GetString("MaskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注信息.
        /// </summary>
        public static string MemoContent {
            get {
                return ResourceManager.GetString("MemoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改邮箱.
        /// </summary>
        public static string ModifyEmail {
            get {
                return ResourceManager.GetString("ModifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改手机.
        /// </summary>
        public static string ModifyMobile {
            get {
                return ResourceManager.GetString("ModifyMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新邮箱.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新手机号码.
        /// </summary>
        public static string NewPhoneNumber {
            get {
                return ResourceManager.GetString("NewPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原邮箱.
        /// </summary>
        public static string OldEmail {
            get {
                return ResourceManager.GetString("OldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原手机号码.
        /// </summary>
        public static string OldPhoneNumber {
            get {
                return ResourceManager.GetString("OldPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号码.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写{0}.
        /// </summary>
        public static string PleaseInputData {
            get {
                return ResourceManager.GetString("PleaseInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置登录密码.
        /// </summary>
        public static string ResetLoginPassword {
            get {
                return ResourceManager.GetString("ResetLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置资金密码.
        /// </summary>
        public static string ResetMoneyPassword {
            get {
                return ResourceManager.GetString("ResetMoneyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转帐.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解绑谷歌验证.
        /// </summary>
        public static string UnbindUserAuthenticator {
            get {
                return ResourceManager.GetString("UnbindUserAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请进行初始化设置.
        /// </summary>
        public static string UserEnterInitialization {
            get {
                return ResourceManager.GetString("UserEnterInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亏盈.
        /// </summary>
        public static string WinLose {
            get {
                return ResourceManager.GetString("WinLose", resourceCulture);
            }
        }
    }
}
