//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayElement() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.DisplayElement", typeof(DisplayElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 用户ID 的當地語系化字串。
        /// </summary>
        public static string AccountID {
            get {
                return ResourceManager.GetString("AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金额 的當地語系化字串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 审核原因 的當地語系化字串。
        /// </summary>
        public static string AuditReason {
            get {
                return ResourceManager.GetString("AuditReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Banner 的當地語系化字串。
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消推荐 的當地語系化字串。
        /// </summary>
        public static string CancelRecommend {
            get {
                return ResourceManager.GetString("CancelRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 投诉ID 的當地語系化字串。
        /// </summary>
        public static string ComplaintID {
            get {
                return ResourceManager.GetString("ComplaintID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 删除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 结束时间 的當地語系化字串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 评价ID 的當地語系化字串。
        /// </summary>
        public static string EvaluationID {
            get {
                return ResourceManager.GetString("EvaluationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 精选 的當地語系化字串。
        /// </summary>
        public static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案 的當地語系化字串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 填写区域 的當地語系化字串。
        /// </summary>
        public static string FillInTheField {
            get {
                return ResourceManager.GetString("FillInTheField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GameCode 的當地語系化字串。
        /// </summary>
        public static string GameCode {
            get {
                return ResourceManager.GetString("GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 游戏图 的當地語系化字串。
        /// </summary>
        public static string GameImage {
            get {
                return ResourceManager.GetString("GameImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 处理时间 的當地語系化字串。
        /// </summary>
        public static string HandleTime {
            get {
                return ResourceManager.GetString("HandleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 热度 的當地語系化字串。
        /// </summary>
        public static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首页公告ID 的當地語系化字串。
        /// </summary>
        public static string HomeAnnouncementID {
            get {
                return ResourceManager.GetString("HomeAnnouncementID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 热门游戏名称 的當地語系化字串。
        /// </summary>
        public static string HotGameName {
            get {
                return ResourceManager.GetString("HotGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收益单ID 的當地語系化字串。
        /// </summary>
        public static string IncomeSlipID {
            get {
                return ResourceManager.GetString("IncomeSlipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 启用状态 的當地語系化字串。
        /// </summary>
        public static string IsActiveStatus {
            get {
                return ResourceManager.GetString("IsActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 审核原因 的當地語系化字串。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 发帖项目 的當地語系化字串。
        /// </summary>
        public static string OptioncOntent {
            get {
                return ResourceManager.GetString("OptioncOntent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 项目ID 的當地語系化字串。
        /// </summary>
        public static string OptionID {
            get {
                return ResourceManager.GetString("OptionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 订单编号 的當地語系化字串。
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 订单时间 的當地語系化字串。
        /// </summary>
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 权限 的當地語系化字串。
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帖子ID 的當地語系化字串。
        /// </summary>
        public static string PostId {
            get {
                return ResourceManager.GetString("PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否同意申请调价 的當地語系化字串。
        /// </summary>
        public static string PriceAdjustment {
            get {
                return ResourceManager.GetString("PriceAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 产品 的當地語系化字串。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 广场担保发帖记录 的當地語系化字串。
        /// </summary>
        public static string PublishPostRecord {
            get {
                return ResourceManager.GetString("PublishPostRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未通过原因 的當地語系化字串。
        /// </summary>
        public static string ReasonForFailure {
            get {
                return ResourceManager.GetString("ReasonForFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推荐 的當地語系化字串。
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推荐游戏 的當地語系化字串。
        /// </summary>
        public static string RecommendGame {
            get {
                return ResourceManager.GetString("RecommendGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 转导网址 的當地語系化字串。
        /// </summary>
        public static string RedirectURL {
            get {
                return ResourceManager.GetString("RedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刷新频率设置 的當地語系化字串。
        /// </summary>
        public static string RefreshFrequencySetting {
            get {
                return ResourceManager.GetString("RefreshFrequencySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 备注 的當地語系化字串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 审核 的當地語系化字串。
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所属角色 的當地語系化字串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名称 的當地語系化字串。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 显示 的當地語系化字串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 电子游戏名称 的當地語系化字串。
        /// </summary>
        public static string SlotGameName {
            get {
                return ResourceManager.GetString("SlotGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 开始时间 的當地語系化字串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 状态 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 开关 的當地語系化字串。
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 内文 的當地語系化字串。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所属第三方 的當地語系化字串。
        /// </summary>
        public static string ThirdPartyOwnership {
            get {
                return ResourceManager.GetString("ThirdPartyOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 标题 的當地語系化字串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 转帐来源 的當地語系化字串。
        /// </summary>
        public static string TransferSource {
            get {
                return ResourceManager.GetString("TransferSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 转帐目标 的當地語系化字串。
        /// </summary>
        public static string TransferTarget {
            get {
                return ResourceManager.GetString("TransferTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 转帐类型 的當地語系化字串。
        /// </summary>
        public static string TransferType {
            get {
                return ResourceManager.GetString("TransferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解锁价格 的當地語系化字串。
        /// </summary>
        public static string UnlockPrice {
            get {
                return ResourceManager.GetString("UnlockPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新游戏图 的當地語系化字串。
        /// </summary>
        public static string UpdateGameImage {
            get {
                return ResourceManager.GetString("UpdateGameImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新密码 的當地語系化字串。
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用户ID 的當地語系化字串。
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用戶名 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 权重 的當地語系化字串。
        /// </summary>
        public static string Weights {
            get {
                return ResourceManager.GetString("Weights", resourceCulture);
            }
        }
    }
}
