//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlatformProductElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatformProductElement() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.PlatformProductElement", typeof(PlatformProductElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 欧博真人 的當地語系化字串。
        /// </summary>
        public static string ABEB {
            get {
                return ResourceManager.GetString("ABEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AG真人 的當地語系化字串。
        /// </summary>
        public static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AG捕鱼 的當地語系化字串。
        /// </summary>
        public static string AGFishing {
            get {
                return ResourceManager.GetString("AGFishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AG 的當地語系化字串。
        /// </summary>
        public static string AGWallet {
            get {
                return ResourceManager.GetString("AGWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AG电子 的當地語系化字串。
        /// </summary>
        public static string AGXin {
            get {
                return ResourceManager.GetString("AGXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AG街机 的當地語系化字串。
        /// </summary>
        public static string AGYoPlay {
            get {
                return ResourceManager.GetString("AGYoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HRB赛马 的當地語系化字串。
        /// </summary>
        public static string AWCHB {
            get {
                return ResourceManager.GetString("AWCHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AWC体育 的當地語系化字串。
        /// </summary>
        public static string AWCSP {
            get {
                return ResourceManager.GetString("AWCSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SV388斗鸡 的當地語系化字串。
        /// </summary>
        public static string AWCSV {
            get {
                return ResourceManager.GetString("AWCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BTI体育 的當地語系化字串。
        /// </summary>
        public static string BTIS {
            get {
                return ResourceManager.GetString("BTIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EVO真人 的當地語系化字串。
        /// </summary>
        public static string EVEB {
            get {
                return ResourceManager.GetString("EVEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 开心电竞 的當地語系化字串。
        /// </summary>
        public static string FYES {
            get {
                return ResourceManager.GetString("FYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IM电竞 的當地語系化字串。
        /// </summary>
        public static string IM {
            get {
                return ResourceManager.GetString("IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IM棋牌 的當地語系化字串。
        /// </summary>
        public static string IMBG {
            get {
                return ResourceManager.GetString("IMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 eBET真人 的當地語系化字串。
        /// </summary>
        public static string IMeBET {
            get {
                return ResourceManager.GetString("IMeBET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JDB电子 的當地語系化字串。
        /// </summary>
        public static string IMJDB {
            get {
                return ResourceManager.GetString("IMJDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 开元棋牌 的當地語系化字串。
        /// </summary>
        public static string IMKY {
            get {
                return ResourceManager.GetString("IMKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PP电子 的當地語系化字串。
        /// </summary>
        public static string IMPP {
            get {
                return ResourceManager.GetString("IMPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JDB/PP/SE 的當地語系化字串。
        /// </summary>
        public static string IMPPWallet {
            get {
                return ResourceManager.GetString("IMPPWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PT电游 的當地語系化字串。
        /// </summary>
        public static string IMPT {
            get {
                return ResourceManager.GetString("IMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PT真人 的當地語系化字串。
        /// </summary>
        public static string IMPTLIVE {
            get {
                return ResourceManager.GetString("IMPTLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PT 的當地語系化字串。
        /// </summary>
        public static string IMPTWallet {
            get {
                return ResourceManager.GetString("IMPTWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SE电子 的當地語系化字串。
        /// </summary>
        public static string IMSE {
            get {
                return ResourceManager.GetString("IMSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 双赢彩票 的當地語系化字串。
        /// </summary>
        public static string IMSG {
            get {
                return ResourceManager.GetString("IMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IM体育 的當地語系化字串。
        /// </summary>
        public static string IMSport {
            get {
                return ResourceManager.GetString("IMSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VR彩票 的當地語系化字串。
        /// </summary>
        public static string IMVR {
            get {
                return ResourceManager.GetString("IMVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JDB捕鱼 的當地語系化字串。
        /// </summary>
        public static string JDBFI {
            get {
                return ResourceManager.GetString("JDBFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 龙城棋牌 的當地語系化字串。
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AMD彩票 的當地語系化字串。
        /// </summary>
        public static string Lottery {
            get {
                return ResourceManager.GetString("Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顶盛彩票 的當地語系化字串。
        /// </summary>
        public static string LotteryByCTS {
            get {
                return ResourceManager.GetString("LotteryByCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PM真人 的當地語系化字串。
        /// </summary>
        public static string OBEB {
            get {
                return ResourceManager.GetString("OBEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PM捕鱼王 的當地語系化字串。
        /// </summary>
        public static string OBFI {
            get {
                return ResourceManager.GetString("OBFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PM体育 的當地語系化字串。
        /// </summary>
        public static string OBSP {
            get {
                return ResourceManager.GetString("OBSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顶盛体育 的當地語系化字串。
        /// </summary>
        public static string OBSPByCTS {
            get {
                return ResourceManager.GetString("OBSPByCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一分快三 的當地語系化字串。
        /// </summary>
        public static string OMKS {
            get {
                return ResourceManager.GetString("OMKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一分六合彩 的當地語系化字串。
        /// </summary>
        public static string OMLHC {
            get {
                return ResourceManager.GetString("OMLHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一分快车 的當地語系化字串。
        /// </summary>
        public static string OMPK10 {
            get {
                return ResourceManager.GetString("OMPK10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一分时时彩 的當地語系化字串。
        /// </summary>
        public static string OMSSC {
            get {
                return ResourceManager.GetString("OMSSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PG电子 的當地語系化字串。
        /// </summary>
        public static string PGSL {
            get {
                return ResourceManager.GetString("PGSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PM棋牌 的當地語系化字串。
        /// </summary>
        public static string PMBG {
            get {
                return ResourceManager.GetString("PMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PM电子 的當地語系化字串。
        /// </summary>
        public static string PMSL {
            get {
                return ResourceManager.GetString("PMSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 老虎机 的當地語系化字串。
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RG电竞 的當地語系化字串。
        /// </summary>
        public static string RG {
            get {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沙巴体育 的當地語系化字串。
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BoardGame棋牌 的當地語系化字串。
        /// </summary>
        public static string TPGameGroup_BoardGame {
            get {
                return ResourceManager.GetString("TPGameGroup_BoardGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 体育电竞 的當地語系化字串。
        /// </summary>
        public static string TPGameGroup_ESport {
            get {
                return ResourceManager.GetString("TPGameGroup_ESport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LIVE真人 的當地語系化字串。
        /// </summary>
        public static string TPGameGroup_LIVE {
            get {
                return ResourceManager.GetString("TPGameGroup_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 老虎机电游 的當地語系化字串。
        /// </summary>
        public static string TPGameGroup_Slot {
            get {
                return ResourceManager.GetString("TPGameGroup_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 瓦力游戏 的當地語系化字串。
        /// </summary>
        public static string WLBG {
            get {
                return ResourceManager.GetString("WLBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 瓦力捕鱼 的當地語系化字串。
        /// </summary>
        public static string WLFishing {
            get {
                return ResourceManager.GetString("WLFishing", resourceCulture);
            }
        }
    }
}
