//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Element {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserRelatedElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRelatedElement() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Element.UserRelatedElement", typeof(UserRelatedElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增银行卡 的本地化字符串。
        /// </summary>
        public static string AddBankCard {
            get {
                return ResourceManager.GetString("AddBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整流水 的本地化字符串。
        /// </summary>
        public static string AdjustFlowAmount {
            get {
                return ResourceManager.GetString("AdjustFlowAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理钱包 的本地化字符串。
        /// </summary>
        public static string AgentWallet {
            get {
                return ResourceManager.GetString("AgentWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主账户余额 的本地化字符串。
        /// </summary>
        public static string AvailableScoresNameByTypeAgent {
            get {
                return ResourceManager.GetString("AvailableScoresNameByTypeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主账户余额(中心) 的本地化字符串。
        /// </summary>
        public static string AvailableScoresNameByTypeDirect {
            get {
                return ResourceManager.GetString("AvailableScoresNameByTypeDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额 的本地化字符串。
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行卡号 的本地化字符串。
        /// </summary>
        public static string BankCard {
            get {
                return ResourceManager.GetString("BankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行类型 的本地化字符串。
        /// </summary>
        public static string BankType {
            get {
                return ResourceManager.GetString("BankType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行户名 的本地化字符串。
        /// </summary>
        public static string CardUser {
            get {
                return ResourceManager.GetString("CardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中心钱包 的本地化字符串。
        /// </summary>
        public static string CenterWallet {
            get {
                return ResourceManager.GetString("CenterWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级转账开关 的本地化字符串。
        /// </summary>
        public static string ChildTransferSwitch {
            get {
                return ResourceManager.GetString("ChildTransferSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (清空) 的本地化字符串。
        /// </summary>
        public static string ClearContent {
            get {
                return ResourceManager.GetString("ClearContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值 的本地化字符串。
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该{0}已被绑定，请重新输入 的本地化字符串。
        /// </summary>
        public static string DuplicateContent {
            get {
                return ResourceManager.GetString("DuplicateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记? 的本地化字符串。
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记密码? 的本地化字符串。
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        public static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结分数 的本地化字符串。
        /// </summary>
        public static string FreezeScore {
            get {
                return ResourceManager.GetString("FreezeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结余额 的本地化字符串。
        /// </summary>
        public static string FreezeScoresNameByTypeAgent {
            get {
                return ResourceManager.GetString("FreezeScoresNameByTypeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结余额(中心) 的本地化字符串。
        /// </summary>
        public static string FreezeScoresNameByTypeDirect {
            get {
                return ResourceManager.GetString("FreezeScoresNameByTypeDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般用户 的本地化字符串。
        /// </summary>
        public static string GeneralUser {
            get {
                return ResourceManager.GetString("GeneralUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GOPAY提现 的本地化字符串。
        /// </summary>
        public static string GOPAY {
            get {
                return ResourceManager.GetString("GOPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入金额 的本地化字符串。
        /// </summary>
        public static string InputAmount {
            get {
                return ResourceManager.GetString("InputAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主账户 的本地化字符串。
        /// </summary>
        public static string MainAccount {
            get {
                return ResourceManager.GetString("MainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 **** 的本地化字符串。
        /// </summary>
        public static string MaskContent {
            get {
                return ResourceManager.GetString("MaskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注信息 的本地化字符串。
        /// </summary>
        public static string MemoContent {
            get {
                return ResourceManager.GetString("MemoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改邮箱 的本地化字符串。
        /// </summary>
        public static string ModifyEmail {
            get {
                return ResourceManager.GetString("ModifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改等级 的本地化字符串。
        /// </summary>
        public static string ModifyLevel {
            get {
                return ResourceManager.GetString("ModifyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改級別(含VIP) 的本地化字符串。
        /// </summary>
        public static string ModifyLevelAndVIPLevel {
            get {
                return ResourceManager.GetString("ModifyLevelAndVIPLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改手机 的本地化字符串。
        /// </summary>
        public static string ModifyMobile {
            get {
                return ResourceManager.GetString("ModifyMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户等级 的本地化字符串。
        /// </summary>
        public static string ModifyUserLevel {
            get {
                return ResourceManager.GetString("ModifyUserLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户级别/VIP等级 的本地化字符串。
        /// </summary>
        public static string ModifyUserLevelAndVIPLevel {
            get {
                return ResourceManager.GetString("ModifyUserLevelAndVIPLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资金密码 的本地化字符串。
        /// </summary>
        public static string MoneyPassword {
            get {
                return ResourceManager.GetString("MoneyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新邮箱 的本地化字符串。
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新手机号码 的本地化字符串。
        /// </summary>
        public static string NewPhoneNumber {
            get {
                return ResourceManager.GetString("NewPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新用戶 的本地化字符串。
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般提现 的本地化字符串。
        /// </summary>
        public static string NormalWithdrawal {
            get {
                return ResourceManager.GetString("NormalWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OKPAY提现 的本地化字符串。
        /// </summary>
        public static string OKPAY {
            get {
                return ResourceManager.GetString("OKPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原邮箱 的本地化字符串。
        /// </summary>
        public static string OldEmail {
            get {
                return ResourceManager.GetString("OldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原手机号码 的本地化字符串。
        /// </summary>
        public static string OldPhoneNumber {
            get {
                return ResourceManager.GetString("OldPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 老用户 的本地化字符串。
        /// </summary>
        public static string OldUser {
            get {
                return ResourceManager.GetString("OldUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户分组 的本地化字符串。
        /// </summary>
        public static string Page_RiskGroup_Setting {
            get {
                return ResourceManager.GetString("Page_RiskGroup_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码 的本地化字符串。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入$1到$2的数字 的本地化字符串。
        /// </summary>
        public static string PleaseInputAmount {
            get {
                return ResourceManager.GetString("PleaseInputAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写{0} 的本地化字符串。
        /// </summary>
        public static string PleaseInputData {
            get {
                return ResourceManager.GetString("PleaseInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真实用户 的本地化字符串。
        /// </summary>
        public static string RealUser {
            get {
                return ResourceManager.GetString("RealUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回收余额 的本地化字符串。
        /// </summary>
        public static string RecycleLeftScores {
            get {
                return ResourceManager.GetString("RecycleLeftScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置登录密码 的本地化字符串。
        /// </summary>
        public static string ResetLoginPassword {
            get {
                return ResourceManager.GetString("ResetLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置资金密码 的本地化字符串。
        /// </summary>
        public static string ResetMoneyPassword {
            get {
                return ResourceManager.GetString("ResetMoneyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户分组 的本地化字符串。
        /// </summary>
        public static string RiskGroupSetting {
            get {
                return ResourceManager.GetString("RiskGroupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择开户银行 的本地化字符串。
        /// </summary>
        public static string SelectOpenAccountBank {
            get {
                return ResourceManager.GetString("SelectOpenAccountBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台添加的后台人员 的本地化字符串。
        /// </summary>
        public static string Source_BackUserAddedByBackSideWeb {
            get {
                return ResourceManager.GetString("Source_BackUserAddedByBackSideWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台添加 的本地化字符串。
        /// </summary>
        public static string Source_FrontUserAddedByBackSideWeb {
            get {
                return ResourceManager.GetString("Source_FrontUserAddedByBackSideWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推广链结 的本地化字符串。
        /// </summary>
        public static string Source_FrontUserAddedByLink {
            get {
                return ResourceManager.GetString("Source_FrontUserAddedByLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级前台添加 的本地化字符串。
        /// </summary>
        public static string Source_FrontUserAddedByParent {
            get {
                return ResourceManager.GetString("Source_FrontUserAddedByParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接注册 的本地化字符串。
        /// </summary>
        public static string Source_FrontUserAddedBySelf {
            get {
                return ResourceManager.GetString("Source_FrontUserAddedBySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极速提现 的本地化字符串。
        /// </summary>
        public static string SpeedWithdrawal {
            get {
                return ResourceManager.GetString("SpeedWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现开关 的本地化字符串。
        /// </summary>
        public static string SwitchUserWithdrawal {
            get {
                return ResourceManager.GetString("SwitchUserWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂冻 的本地化字符串。
        /// </summary>
        public static string TemporaryFreeze {
            get {
                return ResourceManager.GetString("TemporaryFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOPAY提现 的本地化字符串。
        /// </summary>
        public static string TOPAY {
            get {
                return ResourceManager.GetString("TOPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游客 的本地化字符串。
        /// </summary>
        public static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转帐 的本地化字符串。
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转账金额 的本地化字符串。
        /// </summary>
        public static string TransferAmount {
            get {
                return ResourceManager.GetString("TransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认转帐 的本地化字符串。
        /// </summary>
        public static string TransferConfirm {
            get {
                return ResourceManager.GetString("TransferConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转入帐户 的本地化字符串。
        /// </summary>
        public static string TransferInAccount {
            get {
                return ResourceManager.GetString("TransferInAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转出帐户 的本地化字符串。
        /// </summary>
        public static string TransferOutAccount {
            get {
                return ResourceManager.GetString("TransferOutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提款至中心钱包 的本地化字符串。
        /// </summary>
        public static string TransferToCenterWallet {
            get {
                return ResourceManager.GetString("TransferToCenterWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑手机 的本地化字符串。
        /// </summary>
        public static string UnbindPhoneNumber {
            get {
                return ResourceManager.GetString("UnbindPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑谷歌验证 的本地化字符串。
        /// </summary>
        public static string UnbindUserAuthenticator {
            get {
                return ResourceManager.GetString("UnbindUserAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USDT提现 的本地化字符串。
        /// </summary>
        public static string USDT {
            get {
                return ResourceManager.GetString("USDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请进行初始化设置 的本地化字符串。
        /// </summary>
        public static string UserEnterInitialization {
            get {
                return ResourceManager.GetString("UserEnterInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户级别 的本地化字符串。
        /// </summary>
        public static string UserLevel {
            get {
                return ResourceManager.GetString("UserLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string UserNote {
            get {
                return ResourceManager.GetString("UserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名生日 的本地化字符串。
        /// </summary>
        public static string UserRealNameAndBirthday {
            get {
                return ResourceManager.GetString("UserRealNameAndBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱包管理 的本地化字符串。
        /// </summary>
        public static string WalletManagement {
            get {
                return ResourceManager.GetString("WalletManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亏盈 的本地化字符串。
        /// </summary>
        public static string WinLose {
            get {
                return ResourceManager.GetString("WinLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现(RMB) 的本地化字符串。
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现金额 的本地化字符串。
        /// </summary>
        public static string WithdrawalAmount {
            get {
                return ResourceManager.GetString("WithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现申请成功！ 的本地化字符串。
        /// </summary>
        public static string WithdrawalApplicationSuccessful {
            get {
                return ResourceManager.GetString("WithdrawalApplicationSuccessful", resourceCulture);
            }
        }
    }
}
