//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.SlotApiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameLobbyInfo", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.ViewModel.ThirdPar" +
        "ty")]
    [System.SerializableAttribute()]
    public partial class GameLobbyInfo : Web.SlotApiService.BaseGameLobbyList {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullImageUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullImageUrl {
            get {
                return this.FullImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FullImageUrlField, value) != true)) {
                    this.FullImageUrlField = value;
                    this.RaisePropertyChanged("FullImageUrl");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityModel", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.Entity.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.SlotApiService.BaseGameLobbyList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.SlotApiService.GameLobbyInfo))]
    public partial class BaseEntityModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateDateTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDateText {
            get {
                return this.CreateDateTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateTextField, value) != true)) {
                    this.CreateDateTextField = value;
                    this.RaisePropertyChanged("CreateDateText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUser {
            get {
                return this.CreateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserField, value) != true)) {
                    this.CreateUserField = value;
                    this.RaisePropertyChanged("CreateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateDateText {
            get {
                return this.UpdateDateTextField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateDateTextField, value) != true)) {
                    this.UpdateDateTextField = value;
                    this.RaisePropertyChanged("UpdateDateText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateUser {
            get {
                return this.UpdateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateUserField, value) != true)) {
                    this.UpdateUserField = value;
                    this.RaisePropertyChanged("UpdateUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseGameLobbyList", Namespace="http://schemas.datacontract.org/2004/07/JxBackendService.Model.Entity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Web.SlotApiService.GameLobbyInfo))]
    public partial class BaseGameLobbyList : Web.SlotApiService.BaseEntityModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChineseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileGameCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebGameCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChineseName {
            get {
                return this.ChineseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChineseNameField, value) != true)) {
                    this.ChineseNameField = value;
                    this.RaisePropertyChanged("ChineseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishName {
            get {
                return this.EnglishNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishNameField, value) != true)) {
                    this.EnglishNameField = value;
                    this.RaisePropertyChanged("EnglishName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHot {
            get {
                return this.IsHotField;
            }
            set {
                if ((this.IsHotField.Equals(value) != true)) {
                    this.IsHotField = value;
                    this.RaisePropertyChanged("IsHot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileGameCode {
            get {
                return this.MobileGameCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileGameCodeField, value) != true)) {
                    this.MobileGameCodeField = value;
                    this.RaisePropertyChanged("MobileGameCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sort {
            get {
                return this.SortField;
            }
            set {
                if ((this.SortField.Equals(value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebGameCode {
            get {
                return this.WebGameCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WebGameCodeField, value) != true)) {
                    this.WebGameCodeField = value;
                    this.RaisePropertyChanged("WebGameCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SlotApiService.ISlotApiService")]
    public interface ISlotApiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlotApiService/GetGameList", ReplyAction="http://tempuri.org/ISlotApiService/GetGameListResponse")]
        System.Collections.Generic.List<Web.SlotApiService.GameLobbyInfo> GetGameList(string gameLobbyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlotApiService/GetGameList", ReplyAction="http://tempuri.org/ISlotApiService/GetGameListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Web.SlotApiService.GameLobbyInfo>> GetGameListAsync(string gameLobbyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlotApiService/GetJackpotAmount", ReplyAction="http://tempuri.org/ISlotApiService/GetJackpotAmountResponse")]
        string GetJackpotAmount(string gameLobbyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlotApiService/GetJackpotAmount", ReplyAction="http://tempuri.org/ISlotApiService/GetJackpotAmountResponse")]
        System.Threading.Tasks.Task<string> GetJackpotAmountAsync(string gameLobbyType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISlotApiServiceChannel : Web.SlotApiService.ISlotApiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SlotApiServiceClient : System.ServiceModel.ClientBase<Web.SlotApiService.ISlotApiService>, Web.SlotApiService.ISlotApiService {
        
        public SlotApiServiceClient() {
        }
        
        public SlotApiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SlotApiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlotApiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlotApiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Web.SlotApiService.GameLobbyInfo> GetGameList(string gameLobbyType) {
            return base.Channel.GetGameList(gameLobbyType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Web.SlotApiService.GameLobbyInfo>> GetGameListAsync(string gameLobbyType) {
            return base.Channel.GetGameListAsync(gameLobbyType);
        }
        
        public string GetJackpotAmount(string gameLobbyType) {
            return base.Channel.GetJackpotAmount(gameLobbyType);
        }
        
        public System.Threading.Tasks.Task<string> GetJackpotAmountAsync(string gameLobbyType) {
            return base.Channel.GetJackpotAmountAsync(gameLobbyType);
        }
    }
}
