//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Deposit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deposit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Page.Deposit", typeof(Deposit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 充值金额.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附言.
        /// </summary>
        public static string AttachWord {
            get {
                return ResourceManager.GetString("AttachWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收款账号.
        /// </summary>
        public static string BeneficiaryAccount {
            get {
                return ResourceManager.GetString("BeneficiaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收款银行.
        /// </summary>
        public static string BeneficiaryBank {
            get {
                return ResourceManager.GetString("BeneficiaryBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收款方信息.
        /// </summary>
        public static string BeneficiaryInfo {
            get {
                return ResourceManager.GetString("BeneficiaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收款人姓名.
        /// </summary>
        public static string BeneficiaryName {
            get {
                return ResourceManager.GetString("BeneficiaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择充值方式.
        /// </summary>
        public static string ChoiceRecharge {
            get {
                return ResourceManager.GetString("ChoiceRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ，確认刪除尚未完成的充值单?.
        /// </summary>
        public static string ConfirmDeleteDepositOrder {
            get {
                return ResourceManager.GetString("ConfirmDeleteDepositOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付倒数.
        /// </summary>
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 充值限额 最低 $1元 最高 $2元.
        /// </summary>
        public static string DepositLimitRange {
            get {
                return ResourceManager.GetString("DepositLimitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 充值页面已过期！.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一次用? 查看教学.
        /// </summary>
        public static string FirstUse {
            get {
                return ResourceManager.GetString("FirstUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回充值列表.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前往充值.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限额$1元 - $2元.
        /// </summary>
        public static string LimitRange {
            get {
                return ResourceManager.GetString("LimitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您还有“支付宝”充值单未处理.
        /// </summary>
        public static string NotHandlerAlipayOrder {
            get {
                return ResourceManager.GetString("NotHandlerAlipayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先绑定银行卡！.
        /// </summary>
        public static string PleaseBindingBankCard {
            get {
                return ResourceManager.GetString("PleaseBindingBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写充值金额.
        /// </summary>
        public static string PleaseInputAmount {
            get {
                return ResourceManager.GetString("PleaseInputAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平台填写金额应与网银汇款金额完全一致，否则将无法即时到账！.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. 银行转账方式，每天充值处理时间为早上9:00至次日凌晨2:00。.
        /// </summary>
        public static string Tip1 {
            get {
                return ResourceManager.GetString("Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. 若超过两分钟没有到账，请与客服联系。.
        /// </summary>
        public static string Tip2 {
            get {
                return ResourceManager.GetString("Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. 填写的金额须与充值金额一致，否则无法到账。.
        /// </summary>
        public static string Tip3 {
            get {
                return ResourceManager.GetString("Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. 为保障用户资金安全，我们会不定期更换收款银行卡，切勿重复使用之前的记录充值，否则造成充值到错误帐号、资金丢失，平台无法处理。.
        /// </summary>
        public static string Tip4 {
            get {
                return ResourceManager.GetString("Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. 第一次使用USDT？.
        /// </summary>
        public static string UsdtTip1 {
            get {
                return ResourceManager.GetString("UsdtTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. 推荐您使用TronLink（波宝钱包）转账，以保证快速稳定到账.
        /// </summary>
        public static string UsdtTip2 {
            get {
                return ResourceManager.GetString("UsdtTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. 请勿向上述地址充值任何非TRC20_ USDT资产，否则资产将不可找回。.
        /// </summary>
        public static string UsdtTip3 {
            get {
                return ResourceManager.GetString("UsdtTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. 最小充值金额：10 USDT ，小于最小金额的充值将不会上账且无法退回。.
        /// </summary>
        public static string UsdtTip4 {
            get {
                return ResourceManager.GetString("UsdtTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. 如若超过两分钟没有到账，请与客服联系。.
        /// </summary>
        public static string UsdtTip5 {
            get {
                return ResourceManager.GetString("UsdtTip5", resourceCulture);
            }
        }
    }
}
