//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Footer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Footer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Page.Footer", typeof(Footer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英属维尔京群岛（BVI）认证.
        /// </summary>
        public static string BVI {
            get {
                return ResourceManager.GetString("BVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ©版权所有 侵权必究.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常见问题.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英国GC监督委员会.
        /// </summary>
        public static string GC {
            get {
                return ResourceManager.GetString("GC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 马耳他牌照（MGA）认证.
        /// </summary>
        public static string MGA {
            get {
                return ResourceManager.GetString("MGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 官方邮箱.
        /// </summary>
        public static string OfficialMail {
            get {
                return ResourceManager.GetString("OfficialMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菲律宾（PAGCOR）监督牌照.
        /// </summary>
        public static string PAGCOR {
            get {
                return ResourceManager.GetString("PAGCOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐私权政策.
        /// </summary>
        public static string PivacyNotice {
            get {
                return ResourceManager.GetString("PivacyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 理性博彩.
        /// </summary>
        public static string RationalBetting {
            get {
                return ResourceManager.GetString("RationalBetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规则与条款.
        /// </summary>
        public static string Rules_Terms {
            get {
                return ResourceManager.GetString("Rules_Terms", resourceCulture);
            }
        }
    }
}
