//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Register {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Page.Register", typeof(Register).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此帐号已被使用.
        /// </summary>
        public static string AccountExist {
            get {
                return ResourceManager.GetString("AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只能使用英文、数字、汉字与下划线.
        /// </summary>
        public static string AccountFormatValidate {
            get {
                return ResourceManager.GetString("AccountFormatValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-16个字符，汉字每个字以2个字符计算.
        /// </summary>
        public static string AccountLengthValidate {
            get {
                return ResourceManager.GetString("AccountLengthValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此帐号未被使用.
        /// </summary>
        public static string AccountNotExist {
            get {
                return ResourceManager.GetString("AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本人已满18周岁，并同意本网站的条款规则.
        /// </summary>
        public static string AgreeRule {
            get {
                return ResourceManager.GetString("AgreeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在选择最优线路.
        /// </summary>
        public static string ChoiceGoodLine {
            get {
                return ResourceManager.GetString("ChoiceGoodLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速注册.
        /// </summary>
        public static string FasterRegister {
            get {
                return ResourceManager.GetString("FasterRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已有帐号?.
        /// </summary>
        public static string HasAccount {
            get {
                return ResourceManager.GetString("HasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码前后不可输入空格.
        /// </summary>
        public static string PasswordCannotInputSpaces {
            get {
                return ResourceManager.GetString("PasswordCannotInputSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需包含英文字母和数字，可使用特殊字符.
        /// </summary>
        public static string PasswordFormatValidate {
            get {
                return ResourceManager.GetString("PasswordFormatValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入6-16位字符.
        /// </summary>
        public static string PasswordLengthValidate {
            get {
                return ResourceManager.GetString("PasswordLengthValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 与前次输入密码相符.
        /// </summary>
        public static string PasswordMatchWithPreInput {
            get {
                return ResourceManager.GetString("PasswordMatchWithPreInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码强度.
        /// </summary>
        public static string PasswordStrong {
            get {
                return ResourceManager.GetString("PasswordStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请同意本网站的条款规则.
        /// </summary>
        public static string PleaseAgreeRule {
            get {
                return ResourceManager.GetString("PleaseAgreeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请登录.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册中....
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号注册成功.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
    }
}
