//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxBackendService.Resource.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tutorial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tutorial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JxBackendService.Resource.Page.Tutorial", typeof(Tutorial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付宝转帐教学页面.
        /// </summary>
        public static string AlipayTutorialPage {
            get {
                return ResourceManager.GetString("AlipayTutorialPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  拉到最后面，点选到「转账到银行卡」.
        /// </summary>
        public static string ClickTransferToBankCard {
            get {
                return ResourceManager.GetString("ClickTransferToBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成填写资料后点击下一步.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  请点击支付宝中间选项的「转帐」.
        /// </summary>
        public static string PleaseClickAlipayTransfer {
            get {
                return ResourceManager.GetString("PleaseClickAlipayTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请点击微信底部的「我」&amp;gt;「钱包」.
        /// </summary>
        public static string PleaseClickMyWeChatWallet {
            get {
                return ResourceManager.GetString("PleaseClickMyWeChatWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请点击「收付款」的按钮」.
        /// </summary>
        public static string PleaseClickReceivePaymentButton {
            get {
                return ResourceManager.GetString("PleaseClickReceivePaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  请点击「转到银行卡」的按钮.
        /// </summary>
        public static string PleaseClickTransToBankCardButton {
            get {
                return ResourceManager.GetString("PleaseClickTransToBankCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写您的「姓名」、「卡号」、「銀行」.
        /// </summary>
        public static string PleaseInputNameCardBank {
            get {
                return ResourceManager.GetString("PleaseInputNameCardBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微信充值教学页面.
        /// </summary>
        public static string WeChatTutorialPage {
            get {
                return ResourceManager.GetString("WeChatTutorialPage", resourceCulture);
            }
        }
    }
}
